// scripts/env-setup.ts
// Reads .env.setup, applies environment variables to Vercel (preview + production scopes),
// writes a local .env file pointing at the Dev Supabase project,
// and writes .env.test pointing at the Test Supabase project.
// Idempotent: re-running updates existing values.
//
// Implementation notes:
// - Vercel CLI v52 has a non-interactive bug: `vercel env add KEY preview` always returns
//   action_required/git_branch_required in non-tty mode, even with --yes or --value.
//   Workaround: use `vercel api` POST to the REST API for creating env vars (all scopes),
//   and `vercel env rm KEY scope --yes` for deletion (CLI rm works fine).
// - `vercel api` must be run with cwd outside the project directory to avoid the CLI
//   misinterpreting the URL path as a local `api/` subdirectory.
import 'dotenv/config';
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { config as parseEnv } from 'dotenv';

type Scope = 'production' | 'preview' | 'development';

const setup = parseEnv({ path: '.env.setup' }).parsed ?? {};
if (Object.keys(setup).length === 0) {
  console.error('.env.setup not found or empty. Run env:verify first.');
  process.exit(1);
}

// cwd outside the project so vercel api doesn't misparse /vN/... as a local api/ dir
const VERCEL_API_CWD = process.env.TEMP ?? process.env.TMP ?? '/tmp';
const VERCEL_ENV = { ...process.env, GITHUB_TOKEN: '' };

function vercelApiPost(projectId: string, key: string, value: string, scope: Scope) {
  const body = JSON.stringify({ key, value, target: [scope], type: 'encrypted' });
  execSync(`vercel api /v10/projects/${projectId}/env --input -`, {
    cwd: VERCEL_API_CWD,
    input: body,
    env: VERCEL_ENV,
    stdio: ['pipe', 'pipe', 'pipe'],
  });
}

function vercelEnvSet(key: string, value: string, scope: Scope, projectId: string) {
  // Remove existing value (silently ignore if not present).
  try {
    execSync(`vercel env rm ${key} ${scope} --yes`, {
      env: VERCEL_ENV,
      stdio: ['ignore', 'ignore', 'ignore'],
    });
  } catch { /* not present — that's fine */ }
  // Add via REST API (avoids CLI interactive-mode branch-selection bug in v52).
  vercelApiPost(projectId, key, value, scope);
  console.log(`  ✓ ${key} [${scope}]`);
}

// Resolve project ID once
const projectInfoRaw = execSync('vercel api /v9/projects/auction-os', {
  cwd: VERCEL_API_CWD,
  env: VERCEL_ENV,
  stdio: ['pipe', 'pipe', 'pipe'],
}).toString();
const projectInfo = JSON.parse(projectInfoRaw);
const PROJECT_ID: string = projectInfo.id;
console.log(`Project: ${projectInfo.name} (${PROJECT_ID})\n`);

const ENV_VARS = [
  'SUPABASE_URL', 'SUPABASE_ANON_KEY', 'SUPABASE_SERVICE_ROLE_KEY', 'DATABASE_URL',
];

console.log('Pushing env vars to Vercel...\n');

// Production scope ← Prod credentials
for (const k of ENV_VARS) vercelEnvSet(k, setup[`PROD_${k}`]!, 'production', PROJECT_ID);
// VITE_ mirrors for browser-bundled vars
vercelEnvSet('VITE_SUPABASE_URL', setup.PROD_SUPABASE_URL!, 'production', PROJECT_ID);
vercelEnvSet('VITE_SUPABASE_ANON_KEY', setup.PROD_SUPABASE_ANON_KEY!, 'production', PROJECT_ID);

// Preview + Development scopes ← Dev credentials
for (const scope of ['preview', 'development'] as Scope[]) {
  for (const k of ENV_VARS) vercelEnvSet(k, setup[`DEV_${k}`]!, scope, PROJECT_ID);
  vercelEnvSet('VITE_SUPABASE_URL', setup.DEV_SUPABASE_URL!, scope, PROJECT_ID);
  vercelEnvSet('VITE_SUPABASE_ANON_KEY', setup.DEV_SUPABASE_ANON_KEY!, scope, PROJECT_ID);
}

console.log('\nWriting .env (local dev → Dev Supabase) and .env.test (→ Test Supabase)...\n');

const envLocal = [
  `# Auto-generated by env:setup. Do not edit; re-run \`npm run env:setup\` to refresh.`,
  `SUPABASE_URL=${setup.DEV_SUPABASE_URL}`,
  `SUPABASE_ANON_KEY=${setup.DEV_SUPABASE_ANON_KEY}`,
  `SUPABASE_SERVICE_ROLE_KEY=${setup.DEV_SUPABASE_SERVICE_ROLE_KEY}`,
  `DATABASE_URL=${setup.DEV_DATABASE_URL}`,
  `VITE_SUPABASE_URL=${setup.DEV_SUPABASE_URL}`,
  `VITE_SUPABASE_ANON_KEY=${setup.DEV_SUPABASE_ANON_KEY}`,
  `VITE_API_BASE_URL=/api`,
  '',
].join('\n');
writeFileSync('.env', envLocal);

const envTest = [
  `# Auto-generated by env:setup. Used by \`npm test\` (vitest).`,
  `SUPABASE_URL=${setup.TEST_SUPABASE_URL}`,
  `SUPABASE_ANON_KEY=${setup.TEST_SUPABASE_ANON_KEY}`,
  `SUPABASE_SERVICE_ROLE_KEY=${setup.TEST_SUPABASE_SERVICE_ROLE_KEY}`,
  `DATABASE_URL=${setup.TEST_DATABASE_URL}`,
  '',
].join('\n');
writeFileSync('.env.test', envTest);

console.log('Done. .env and .env.test written. Vercel env vars synced.');
